name: Football Data Analysis

on:
  workflow_dispatch:

jobs:
  football-analysis:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    
    steps:
    - uses: actions/checkout@v3


    - name: Install additional R packages
      run: |
        install.packages(c(
          "janitor",
        ), repos = "https://cloud.r-project.org")
      shell: Rscript {0}
      
    - name: Run R script
      run: |
        Rscript football_analysis.R
        
    - name: Check if data file was created
      run: |
        ls -la
        cat data.json | head -20
        
    - name: Commit data file
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Premier League data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
